### ISSUE TITLE
Not all protos files are required

### ISSUE THREAD

**Issue by nicolas-besnard** [nabeelamjad/poke-api#15]
I think you need to require all the Protos files.

It's impossible to retrieve the ID of a Pokemon for example (you get `:RATTATA`, and the `POGOProtos.Enums.PokemonId` is required to retrieve the pokedex index of the pokemon)

**Comment by nabeelamjad** [comment]
Which request(s) is this needed for? The way protobufs works is that the request needs to have the `pokemon_id` linked to that Protobuf, though it might be confusing because `pokemon_id` doesn't always refer to the Pokedex number.

Take for example [ReleasePokemon](https://github.com/nabeelamjad/poke-api/blob/d74611e7899f697d57ef0baa2d27beab853b0d4d/lib/poke-api/POGOProtos/Networking/Requests/Messages/ReleasePokemonMessage.rb), `pokemon_id` refers to your unique pokemon id (obtained via `get_inventory`, example [here](https://github.com/nabeelamjad/poke-api/issues/13)). 

However if you look at [EncounterTutorialComplete](https://github.com/nabeelamjad/poke-api/blob/d74611e7899f697d57ef0baa2d27beab853b0d4d/lib/poke-api/POGOProtos/Networking/Requests/Messages/EncounterTutorialCompleteMessage.rb) it refers to the Pokedex entry directly (working as intended) as it does not refer to your unique Pokemon.

**Comment by nicolas-besnard** [comment]
For instance with `get_inventory`, you will get a JSON with the following hash for each Pokemon in your inventory

``` ruby
 {:id=>17999104379928447950, :pokemon_id=>:ONIX
```

What I want to do, is getting the Pokemon's Pokedex ID (instead of `:ONIX`).

**Comment by nabeelamjad** [comment]
Aha, this actually seems intended by the protobufs (https://github.com/nabeelamjad/poke-api/blob/master/lib/poke-api/POGOProtos/Data/PokemonData.rb#L12). It maps the given number to a name by default, you may have to use custom conversion to change it back (I can provide a sample code on how to do that if you wish).

**Comment by nicolas-besnard** [comment]
The mapping already exists with the protobufs, It seems strange to have to
redefine my own enum.

**Comment by nabeelamjad** [comment]
Here is how you could use it, unfortunately unless you want to change the Protobufs or fork it and remove the reference to PokemonID this is the only workaround I know of.

``` ruby
require 'poke-api'
require 'poke-api/POGOProtos/Enums/PokemonId' # You don't have to load this file after your response as it will be loaded.

def fetch_pokemon_id(name)
  POGOProtos::Enums::PokemonId.const_get(name)
end

fetch_pokemon_id(:ONIX)
 => 95
```

To give you an insight what's happening internally, the protobufs are returning the ID 95 but because we (the protobufs for pokego) have an enum mapped to the ID it will map that like so:

``` ruby
POGOProtos::Enums::PokemonId.lookup(95)
 => :ONIX
```

Which then returns :ONIX instead of your ID because of the enum mapping.

**Comment by nicolas-besnard** [comment]
Indeed, your solution works :)
